spring:
  data:
    mongodb:
      host: host.docker.internal
      username: root
      password: example
      database: local
      authentication-database: admin
  # security:
  #   user:
  #     name: user
  #     password: "{noop}password"

logging:
  level:
    de.mp.istint.server: debug
    org.springframework.data: info      
    org.springframework.security.authentication: debug