spring:
  data:
    mongodb:
      host: override this in application-local.yml
      username: override this in application-local.yml
      password: override this in application-local.yml
      database: override this in application-local.yml
      authentication-database: override this in application-local.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-test.juelps.de/realms/iracing-tools-test
server:
  compression:
    enabled: true
    mime-types:
    - application/json  
    - application/hal+json
    min-response-size: 1024
  # security:
  #   user:
  #     name: user
  #     password: "{noop}password"

logging:
  level:    
    '[de.mp.istint.server]': debug
    '[org.springframework.data]': info      
    #org.springframework.security.authentication: debug
    #org.springframework.security: debug


istint:
  cors:
    allowedOrigins: 
      - '*'
    allowedMethods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
    allowedHeaders:
      - '*'
    allowCredentials: true
  


