spring:
  data:
    mongodb:
      host: host.docker.internal
      username: root
      password: example
      database: local
      authentication-database: admin

logging:
  level:
    org.springframework.data: debug      