name: Build image on Tag
on:
  push:
    # branches: [mpapenbr/issue4]
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy to docker
        run: cp target/istint-backend.jar docker/istint-backend.jar

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: docker
          registry: docker.pkg.github.com
          repository: mpapenbr/istint-backend/istint-backend
          # tags: test
          tag_with_ref: true
